# Generated by Django 2.1.3 on 2018-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20181201_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genregroups',
            name='name',
            field=models.CharField(help_text='Enter genre group name', max_length=150, unique=True),
        ),
    ]
