# Generated by Django 2.1.3 on 2018-12-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20181201_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genredepends',
            unique_together={('genre_group', 'genre')},
        ),
    ]
