# Generated by Django 2.1.3 on 2018-12-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20181201_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='genregroups',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
