# Generated by Django 2.1.3 on 2018-12-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_genregroups_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genregroups',
            options={'ordering': ['-created']},
        ),
    ]
