# Generated by Django 2.1.3 on 2018-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20181203_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genredepends',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='genredepends',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genredepends',
            name='genre_group',
        ),
        migrations.AddField(
            model_name='genregroups',
            name='genre',
            field=models.ManyToManyField(related_name='genre_group', to='store.Genre'),
        ),
        migrations.DeleteModel(
            name='GenreDepends',
        ),
    ]
